services:
  db:
    container_name: butte-db
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    container_name: butte-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: air main.go -b 0.0.0.0
    restart: on-failure
    depends_on:
      - db
      - redis
